### ISSUE TITLE
Issue with rasterizer

### ISSUE THREAD

**Issue by GopiRajuMatta** [r4dl/StopThePop-Rasterization#4]
Hello,

Rasterizer is compiled properly. But when I run below command.

python train.py --splatting_config configs/hierarchical.json -s /home/gopi/Desktop/Gopi/FLAVORS/Our_Dataset/Images/Set-1/0

This is the error.

Traceback (most recent call last):
  File "/home/gopi/StopThePop/train.py", line 17, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/gopi/StopThePop/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, ExtendedSettings, GaussianRasterizer
  File "/home/gopi/anaconda3/envs/wg/lib/python3.11/site-packages/diff_gaussian_rasterization/__init__.py", line 203, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/gopi/anaconda3/envs/wg/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/gopi/anaconda3/envs/wg/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gopi/anaconda3/envs/wg/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gopi/anaconda3/envs/wg/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'diff_gaussian_rasterization.SortQueueSizes'> for field queue_sizes is not allowed: use default_factory

How to resolve this?

Thank you
Gopi

**Comment by r4dl** [comment]
Hi,
this [pull request](https://github.com/r4dl/StopThePop-Rasterization/pull/2) (which we will merge soon) likely resolves your issue.

Best,
Lukas
